apiVersion: v1
kind: Service
metadata:
  labels:
    app: coredns-svc-lb
  name: coredns-svc-lb
  namespace: kube-system
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 172.17.255.10
  ipFamilies:
  - IPv4
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
