apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: netperfs.app.example.com
spec:
  group: app.example.com
  names:
    kind: Netperf
    listKind: NetperfList
    plural: netperfs
    singular: netperf
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string # Тип данных поля ApiVersion
            kind:
              type: string # Тип данных поля kind
            metadata:
              type: object # Тип поля metadata
              properties: # Доступные параметры и их тип данных поля metadata (словарь)
                name:
                  type: string
            spec:
              type: object
              properties:
                serverNode:
                  type: string
                clientNode:
                  type: string
              required:
              - serverNode
              - clientNode
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true


