apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paymentservice
  namespace: microservices-demo
spec:
  chart:
    spec:
      chart: ./deploy/charts/paymentservice
      sourceRef:
        kind: GitRepository
        name: microservices-demo
      reconcileStrategy: Revision
  interval: 2m0s
  targetNamespace: microservices-demo
  values:
    image:
      repository: vradnit/paymentservice # {"$imagepolicy": "microservices-demo:paymentservice:name"}
      tag: v0.0.1 # {"$imagepolicy": "microservices-demo:paymentservice:tag"}
