apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frontend
  namespace: microservices-demo
spec:
  chart:
    spec:
      chart: ./deploy/charts/frontend
      sourceRef:
        kind: GitRepository
        name: microservices-demo
      reconcileStrategy: Revision
  interval: 2m0s
  targetNamespace: microservices-demo
  values:
    image:
      repository: vradnit/frontend # {"$imagepolicy": "microservices-demo:frontend:name"}
      tag: v0.0.1 # {"$imagepolicy": "microservices-demo:frontend:tag"}
