apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: recommendationservice
  namespace: microservices-demo
spec:
  chart:
    spec:
      chart: ./deploy/charts/recommendationservice
      sourceRef:
        kind: GitRepository
        name: microservices-demo
      reconcileStrategy: Revision
  interval: 2m0s
  targetNamespace: microservices-demo
  values:
    image:
      repository: vradnit/recommendationservice # {"$imagepolicy": "microservices-demo:recommendationservice:name"}
      tag: v0.0.1 # {"$imagepolicy": "microservices-demo:recommendationservice:tag"}
