apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: busybox
    name: busybox
    volumeMounts:
    - mountPath: "/data"
      name: volume-storage-pod
  volumes:
  - name: volume-storage-pod
    persistentVolumeClaim:
      claimName: storage-pvc
