apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: web
  - name: metrics
    port: 9113
    protocol: TCP
    targetPort: metrics
