apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx
  labels:
    app: nginx
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app: nginx
  endpoints:
  - port: metrics
