apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: image-roductcatalogservice
  newName: gcr.io/google-samples/microservices-demo/productcatalogservice
  newTag: v0.1.3

namePrefix:
  "prod-"

namespace: hipster-shop-prod

commonLabels:
  environment: hipster-shop-prod

commonAnnotations:
  appVersion: 0.1.3

patchesStrategicMerge:
- productcatalogservice-resources.yaml
