ssh_pub_key = File.readlines("/root/.ssh/id_rsa.pub").first.strip

$script1 = <<-SCRIPT
echo start custom provizioning...

ip r d default via 10.0.2.2 && ip r a default via 192.168.56.1

echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
sudo bash -c "echo #{ssh_pub_key} >> /root/.ssh/authorized_keys"
SCRIPT


Vagrant.configure("2") do |config|

  (1..1).each do |vmid|
    vmname = "master-#{vmid}"
    vmname_ip = "192.168.56.10#{vmid}"

    config.vm.define vmname do |node|
      node.vm.network "private_network", ip: vmname_ip
      node.vm.hostname = vmname
      node.vm.define vmname
      node.vm.box_download_insecure = true
      node.vm.box = "ubuntu/bionic64"
      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "8192"
        vb.cpus = 2
      end

      node.vm.provision "shell", inline: $script1

    end
  end

  (1..3).each do |vmid|
    vmname = "worker-#{vmid}"
    vmname_ip = "192.168.56.11#{vmid}"

    config.vm.define vmname do |node|
      node.vm.network "private_network", ip: vmname_ip
      node.vm.hostname = vmname
      node.vm.define vmname
      node.vm.box_download_insecure = true
      node.vm.box = "ubuntu/bionic64"
      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "4096"
        vb.cpus = 2
      end

      node.vm.provision "shell", inline: $script1

    end
  end

end
