apiVersion: v1
kind: Pod
metadata:
  name: vault-agent-example
  namespace: vault
spec:
  serviceAccountName: vault-auth

  volumes:
  - configMap:
      items:
      - key: vault-agent-config.hcl
        path: vault-agent-config.hcl
      - key: consul-template-config.hcl
        path: consul-template-config.hcl
      name: example-vault-agent-config
    name: config
  - emptyDir: {}
    name: shared-data
  - emptyDir: {}
    name: token
  initContainers:
  - name: vault-agent
    image: vault
    args:
    - agent
    - -config=/etc/vault/vault-agent-config.hcl
    - -log-level=debug
    env:
    - name: SKIP_SETCAP
      value: "true"
    - name: VAULT_ADDR
      value: http://vault:8200
    volumeMounts:
    - mountPath: /etc/vault/vault-agent-config.hcl
      subPath: vault-agent-config.hcl
      name: config
    - mountPath: /home/vault
      name: token
  containers:
  - name: consul-template
    image: hashicorp/consul-template:alpine
    args:
    - -config=/etc/consul-template/consul-template-config.hcl
    env:
    - name: VAULT_ADDR
      value: http://vault:8200
    volumeMounts:
    - mountPath: /etc/consul-template/consul-template-config.hcl
      subPath: consul-template-config.hcl
      name: config
    - mountPath: /home/vault
      name: token
    - mountPath: /etc/secrets
      name: shared-data
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: shared-data
