expose:
  type: ingress
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: "harbor.radnit.ru"
  ingress:
    hosts:
      core: harbor.radnit.ru
    controller: default
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-production"
      cert-manager.io/acme-challenge-type: http01
externalURL: https://harbor.radnit.ru

notary:
  enabled: false
