apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: recommendationservice
spec:
  environments:
    stage:
      defaultNamespace: hipster-shop-stage
      server: https://192.168.0.10:6443
    prod:
      defaultNamespace: hipster-shop
      server: https://192.168.0.10:6443
  vars: {}
