repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

helmDefaults:
  wait: true
  timeout: 900
  createNamespace: true

releases:
  - name: postgresql
    labels:
      release: postgresql
    namespace: db
    chart: bitnami/postgresql
    version: 12.1.6
    values:
    - global:
        postgresql:
          auth:
            postgresPassword: "superpass"
            username: "pguser"
            password: "pguserpass"
            database: "testdb"
