apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc-clone
spec:
  storageClassName: csi-hostpath-sc
  dataSource:
    name: storage-pvc
    kind: PersistentVolumeClaim
    apiGroup: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
