ssh_pub_key = File.readlines("/root/.ssh/id_rsa.pub").first.strip

$script1 = <<-SCRIPT
echo start base provizioning...

ip r d default via 10.0.2.2 && ip r a default via 192.168.56.1
nmcli con mod 'enp0s3' ipv4.ignore-auto-dns yes && nmcli con mod 'enp0s3' ipv4.dns "192.168.0.1" && nmcli dev reapply enp0s3

echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
mkdir /root/.ssh && echo #{ssh_pub_key} >> /root/.ssh/authorized_keys && chmod -R go-rwx /root/.ssh
SCRIPT

$script2 = <<-SCRIPT
echo start lb provizioning...

sed -i 's/SELINUX=enforcing/SELINUX=permissive/g' /etc/selinux/config
setenforce Permissive

dnf install --assumeyes --quiet python3
update-alternatives --set python /usr/bin/python3
SCRIPT


Vagrant.configure("2") do |config|
  (1..2).each do |vmid|
    vmname = "lb-#{vmid}"
    vmname_ip = "192.168.56.9#{vmid}"

    config.vm.define vmname do |node|
      node.vm.network "private_network", ip: vmname_ip
      node.vm.hostname = vmname
      node.vm.define vmname
      node.vm.box_download_insecure = true
      node.vm.box = "almalinux/8"
      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "1024"
        vb.cpus = 2
      end

      node.vm.provision "lb", type: "shell", inline: $script2
      node.vm.provision "base", type: "shell", inline: $script1

    end
  end

  (1..3).each do |vmid|
    vmname = "master-#{vmid}"
    vmname_ip = "192.168.56.10#{vmid}"

    config.vm.define vmname do |node|
      node.vm.network "private_network", ip: vmname_ip
      node.vm.hostname = vmname
      node.vm.define vmname
      node.vm.box_download_insecure = true
      node.vm.box = "almalinux/8"
      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "4096"
        vb.cpus = 2
      end

      node.vm.provision "shell", inline: $script1

    end
  end

  (1..2).each do |vmid|
    vmname = "worker-#{vmid}"
    vmname_ip = "192.168.56.11#{vmid}"

    config.vm.define vmname do |node|
      node.vm.network "private_network", ip: vmname_ip
      node.vm.hostname = vmname
      node.vm.define vmname
      node.vm.box_download_insecure = true
      node.vm.box = "almalinux/8"
      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "2048"
        vb.cpus = 2
      end

      node.vm.provision "shell", inline: $script1

    end
  end

end
