repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io

helmDefaults:
  wait: true
  timeout: 300
  createNamespace: true

releases:
  - name: ingress-nginx
    labels:
      release: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.3.0
    values:
    - "./ingress-nginx.values.yaml"
  - name: cert-manager
    labels:
      release: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.10.0
    values:
    - installCRDs: true
  - name: cert-manager-clusterissuers
    labels:
      release: cert-manager
    chart: ../kubernetes-templating/helmfile/charts/cert-manager-clusterissuers
    values:
    - email: vradnit@gmail.com
