repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

helmDefaults:
  wait: true
  timeout: 300
  createNamespace: true

releases:
  - name: kube-prometheus
    labels:
      release: kube-prometheus
    namespace: observability
    chart: prometheus-community/kube-prometheus-stack
    version: 42.0.0
    values:
    - "./prometheus-operator.values.yaml"
    - grafana:
        dashboards:
          default:
            nginx-ingress-custom:
              json: | {{- readFile "./nginx-ingress.json" | nindent 16 }}
 
  - name: elasticsearch-exporter
    labels:
      release: elasticsearch-exporter
    namespace: observability
    chart: prometheus-community/prometheus-elasticsearch-exporter
    version: 4.15.1
    values:
    - "./prometheus-elasticsearch-exporter.values.yaml"
