ingress:
  enabled: true
  className: nginx
  annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-production"
      cert-manager.io/acme-challenge-type: http01
  hosts:
    - host: kibana.radnit.ru
      paths:
        - path: /
  tls:
  - secretName: kibana.radnit.ru
    hosts:
    - kibana.radnit.ru

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-m-1
          - k8s-m-2
          - k8s-m-3

tolerations:
- key: node-role
  operator: Equal
  value: infra
  effect: NoSchedule
