loki:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k8s-m-1
            - k8s-m-2
            - k8s-m-3

  tolerations:
  - key: node-role
    operator: Equal
    value: infra
    effect: NoSchedule

promtail:
  tolerations:
  - effect: NoSchedule
    operator: Exists

grafana:
  sidecar:
    datasources:
      enabled: false
