---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-iptables-tailer
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-iptables-tailer
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["patch","create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-iptables-tailer
subjects:
  - kind: ServiceAccount
    name: kube-iptables-tailer
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kube-iptables-tailer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: "apps/v1"
kind: "DaemonSet"
metadata:
  name: "kube-iptables-tailer"
  namespace: "kube-system"
spec:
  selector:
    matchLabels:
      app: "kube-iptables-tailer"
  template:
    metadata:
      labels:
        app: "kube-iptables-tailer"
    spec:
      serviceAccountName: kube-iptables-tailer
      containers:
        - name: "kube-iptables-tailer"
          command:
            - "/kube-iptables-tailer"
          env:
            - name: "JOURNAL_DIRECTORY"
              value: "/run/log/journal"
            - name: "POD_IDENTIFIER"
              value: "name"
            - name: "IPTABLES_LOG_PREFIX"
              value: "calico-packet:"
            - name: "LOG_LEVEL"
              value: "info"
          image: "honestica/kube-iptables-tailer:master-91"
          imagePullPolicy: Always
          volumeMounts:
            - name: "iptables-logs"
              mountPath: "/run/log"
              readOnly: true
      volumes:
        - name: "iptables-logs"
          hostPath:
            path: "/run/log"
