apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: vradnit/hipster-frontend:v0.0.1
    name: frontend
    env:
    - name: LISTEN_ADDR
      value: "0.0.0.0"
    - name: PORT
      value: "8000"
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: "192.168.0.1"
    - name: CURRENCY_SERVICE_ADDR
      value: "192.168.0.2"
    - name: CART_SERVICE_ADDR
      value: "192.168.0.3"
    - name: RECOMMENDATION_SERVICE_ADDR
      value: "192.168.0.4"
    - name: CHECKOUT_SERVICE_ADDR
      value: "192.168.0.5"
    - name: SHIPPING_SERVICE_ADDR
      value: "192.168.0.6"
    - name: AD_SERVICE_ADDR
      value: "192.168.0.7"
    resources: {}
    ports:
    - name: http
      containerPort: 8000
  dnsPolicy: ClusterFirst
  restartPolicy: Never
